backend:
  name: git-gateway
  repo: naaman10/sarah
  branch: main # Branch to update (optional; defaults to master)
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "Home"
        file: "index.markdown"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "home" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "SEO Description", name: "description", widget: "string", required: true, pattern: ['.{160,}', "Must have at least 160 characters"] }
          - label: "Hero Banner"
            name: "hero_banner"
            widget: "object"
            summary: "{{ fields.title }}"
            fields:
             - { label: "Title", name: "title", widget: "string" }
             - { label: "Position", name: "position", widget: "string" }
             - { label: "Location", name: "location", widget: "string" }
             - { label: "Image", name: "image", widget: "string" }
             - { label: "Image Alt", name: "alt", widget: "string"}
             - { label: "Button Text", name: "button-text", widget: "string" }
             - { label: "Button Link", name: "button-link", widget: "string" }
          - label: "About Section"
            name: "about"
            widget: "object"
            summary: "{{ fields.title }}"
            fields:
             - { label: "Title", name: "title", widget: "string" }
             - { label: "Text", name: "text", widget: "markdown" }
             - { label: "Buttons", name: "buttons", widget: "list", min: 1, max: 2, fields:
              - { label: "Button Text", name: "button-text", widget: "string" }
              - { label: "Button Link", name: "button-link", widget: "string" }
             }
          - label: "Contact Section"
            name: "contact"
            widget: "object"
            summary: "{{ fields.title }}"
            fields:
             - label: "Title"
               name: "title"
               widget: "string" 
             - label: "Intro text"
               name: "intro"
               widget: "markdown"
             - label: "Form Title"
               name: "form-title"
               widget: "string"
             - label: "Form Text"
               name: "form-text"
               widget: "markdown"
             - label: "Contact Info"
               name: "contact"
               widget: "list"
               fields:
               - label: "Type"
                 name: "type"
                 widget: "select"
                 options: ["Email", "LinkedIn", "Instagram", "Telephone", "BACP"]
               - label: "Value"
                 name: "value"
                 widget: "string"
          - label: "Services Section"
            name: "services"
            widget: "object"
            summary: "{{ fields.title }}"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Intro text"
                name: "intro"
                widget: "markdown"
              - label: "Services"
                name: "services"
                widget: "list"
                fields:
                  - label: "Service name"
                    name: "service-name"
                    widget: "string"
                  - label: "Service text"
                    name: "service-text"
                    widget: "markdown"
                    pattern: ["^.{0,40}$", "Must not exceed 40 characters"]
                  - label: "Service link"
                    name: "service-link"
                    widget: "string"
                  - label: "Service link text"
                    name: "service-link-text"
                    widget: "string"
  - name: "config"
    label: "Config"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "navigation"
        file: "_data/navigation.yml"
        fields:
          - label: "Navigation Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
      - label: "Site Data"
        name: "site_data"
        file: "_data/sitedata.yml"
        fields:
          - label: "Thanks Title"
            name: "thanks-title"
            widget: "string"
          - label: "Thanks Text"
            name: "thanks-text"
            widget: "markdown"
          - label: "Contact Form"
            name: "contact-form"
            widget: "object"
            fields:
              - { label: "Email Address", name: "email-field", widget: "string" }
              - { label: "Name", name: "name-field", widget: "string" }
              - { label: "Message", name: "message-field", widget: "string" }
              - { label: "Consent Text", name: "consent-message", widget: "string" }
              - { label: "Submit Button", name: "submit-button", widget: "string" }
      - label: "Footer"
        name: "footer"
        file: "_data/footer.yml"
        fields:
          - label: "Footer Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
              
              