backend:
  name: git-gateway
  repo: naaman10/sarah
  branch: main # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "Home"
        file: "index.markdown"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "home" }
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown, required: false}
          - label: Team
            name: team
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Photo, name: photo, widget: image}